### ISSUE TITLE
Library not available in Arduino Library Manager

### ISSUE THREAD

**Issue by beegee-tokyo** [sitronlabs/SitronLabs_OPT3001_Arduino_Library#1]
Hello,
Nice library. Do you have any plans to release it in the Arduino Library Manager?

Installing in Arduino IDE as ZIP library fails unfortunately, I had to manually copy the folder and then move the **`opt3001.h`** from **`include`** folder into **`src`** folder to get it to work.

**Comment by nschurando** [comment]
Hi Bernd, thank you for the feedback. I will publish an update in the next days.

**Comment by nschurando** [comment]
Should work as expected since v0.1.1 👍.
